prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix owl:  <http://www.w3.org/2002/07/owl#> 
prefix xsd:  <http://www.w3.org/2001/XMLSchema#> 
prefix sur:  <https://w3id.org/survey-ontology#> 
prefix prov: <http://www.w3.org/ns/prov#> 
prefix ggdm: <https://vito.be/schema/ggdm#>

SELECT 
?question ?completedQuestion ?answer ?date ?person ?session
WHERE { 
  ?session ggdm:sessionTimestamp ?date ;
    prov:wasAssociatedWith ?person .
  ?completedQuestion sur:answeredIn ?session ;
    sur:hasAnswer ?answer ;
    sur:completesQuestion ?question .
}
